### PR TITLE
2) #2544 changing onInput to onChange for countries dropdown

### PR DESCRIPTION
**Pull request by naazy**
https://github.com/OxfordAbstracts/application/issues/2544 changing onInput to onChange for countries dropdown

### CODE REVIEW

**Comment by iteles** [comment]
@naazy Have you also been able to deploy this branch to staging2 and tested the application on IE and Chrome?

**Comment by naazy** [comment]
@iteles I've tested it on IE via connecting to my macbook IP address from my windows machine. I'm just about to test deploying to npm and upping the version on the main app to double check that it integrates okay with the main app.

**Comment by naazy** [comment]
@Conorc1000 Because master didn't seem to be up-to-date, I've brought over the most recent elm-authors version from npm which is why this PR is quite big. Please confirm that the correct most recent version on npm is the 'real' master. If you want to see the actual new changes to this PR, then please see https://github.com/OxfordAbstracts/elm-authors/compare/oneOrMultiplePresenters...countriesAuthorBug

I will also make another PR for what I believe is the 'real' master so we can close #17

**Comment by naazy** [comment]
Also @Conorc1000 please see this: https://github.com/OxfordAbstracts/elm-authors/issues/18 THANKS

**Pull request merged**
